// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatriotMechanical.API.Infrastructure.Data;

#nullable disable

namespace PatriotMechanical.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310124941_AddColumnRole")]
    partial class AddColumnRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.ApBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("ApBills");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("HoldReasonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceTitanAppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanLocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TechnicianCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.AppointmentTechnician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<long>("ServiceTitanAppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanTechnicianId")
                        .HasColumnType("bigint");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentTechnicians");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.ArAlertDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanySettingsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ArAlertDismissals");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BoardColumnId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoardColumnId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("BoardCards");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardCardNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<Guid>("BoardCardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardCardId");

                    b.ToTable("BoardCardNotes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColumnRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BoardColumns");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CompanySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ArAlertBalanceThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ArAlertDays30Threshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ArAlertDays60Threshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ArAlertDays90Threshold")
                        .HasColumnType("numeric");

                    b.Property<bool>("ArAlertOn30Days")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArAlertOn60Days")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArAlertOn90Days")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArAlertOnBalanceAmount")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditCardFeePercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("text");

                    b.Property<string>("ServiceTitanAppKey")
                        .HasColumnType("text");

                    b.Property<string>("ServiceTitanClientId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceTitanClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ServiceTitanTenantId")
                        .HasColumnType("text");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncedFromServiceTitan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<long>("ServiceTitanCustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ServiceTitanModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<long>("ServiceTitanContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CustomerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ServiceTitanLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerLocations");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WarrantyExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WarrantyRegistered")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Estimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstimateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncedFromServiceTitan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ServiceTitanCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanEstimateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanJobId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SoldOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceTitanEstimateId")
                        .IsUnique();

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.EstimateFollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId")
                        .IsUnique();

                    b.ToTable("EstimateFollowUps");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.EstimateFollowUpNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowUpId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpId");

                    b.ToTable("EstimateFollowUpNotes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceRemaining")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedFromServiceTitan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServiceTitanInvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.LocationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<long>("ServiceTitanContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationContacts");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CreditCardFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.ServiceTitanSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContinuationToken")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceTitanSyncStates");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Subcontractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subcontractors");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.SubcontractorEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubcontractorId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("SubcontractorEntries");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyCost")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanySettingsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanySettingsId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.VendorBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceRemaining")
                        .HasColumnType("numeric");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("VendorBills");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WarrantyClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClaimFiledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CreditAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<bool>("DefectivePartReturned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DefectiveReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpectedShipDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InstalledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean");

                    b.Property<string>("JobNumber")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("PartModelNumber")
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PartReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReturnJobNumber")
                        .HasColumnType("text");

                    b.Property<string>("RmaNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<string>("UnitModelNumber")
                        .HasColumnType("text");

                    b.Property<string>("UnitSerialNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("WarrantyClaims");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WarrantyClaimNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WarrantyClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarrantyClaimId");

                    b.ToTable("WarrantyClaimNotes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTypeName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncedFromServiceTitan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MarginPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<long>("ServiceTitanCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTitanLocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ServiceTitanModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalLaborCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMaterialCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRevenueCalculated")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrderLabor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BilledHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BilledRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HourlyCostSnapshot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderLabors");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OriginalCalculatedPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasColumnType("numeric");

                    b.Property<bool>("WasPriceOverridden")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderMaterials");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.ApBill", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Bills")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.AppointmentTechnician", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Technicians")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.ArAlertDismissal", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardCard", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.BoardColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("BoardColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Column");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardCardNote", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.BoardCard", "Card")
                        .WithMany("Notes")
                        .HasForeignKey("BoardCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CustomerContact", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CustomerLocation", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Customer");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Estimate", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.EstimateFollowUp", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Estimate", "Estimate")
                        .WithOne("FollowUp")
                        .HasForeignKey("PatriotMechanical.API.Domain.Entities.EstimateFollowUp", "EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.EstimateFollowUpNote", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.EstimateFollowUp", "FollowUp")
                        .WithMany("Notes")
                        .HasForeignKey("FollowUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowUp");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithOne("Invoice")
                        .HasForeignKey("PatriotMechanical.API.Domain.Entities.Invoice", "WorkOrderId");

                    b.Navigation("Customer");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.LocationContact", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.CustomerLocation", "Location")
                        .WithMany("Contacts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.SubcontractorEntry", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Subcontractor", "Subcontractor")
                        .WithMany("Entries")
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcontractor");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.User", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.CompanySettings", "Company")
                        .WithMany()
                        .HasForeignKey("CompanySettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.VendorBill", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Vendor");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WarrantyClaim", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WarrantyClaimNote", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.WarrantyClaim", "Claim")
                        .WithMany("Notes")
                        .HasForeignKey("WarrantyClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Customer", "Customer")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatriotMechanical.API.Domain.Entities.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrderLabor", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("LaborEntries")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.HasOne("PatriotMechanical.API.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.HasOne("PatriotMechanical.API.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("MaterialEntries")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardCard", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.BoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.CustomerLocation", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Estimate", b =>
                {
                    b.Navigation("FollowUp");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.EstimateFollowUp", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Subcontractor", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WarrantyClaim", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PatriotMechanical.API.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("LaborEntries");

                    b.Navigation("MaterialEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
